package com.alvaroquintana.adivinabandera.application

import android.app.Application
import coil3.ImageLoader
import coil3.SingletonImageLoader
import coil3.svg.SvgDecoder
import com.alvaroquintana.adivinabandera.application.di.AppGraph
import dev.zacsweers.metro.createGraphFactory

class AdivinaApp : Application() {

    /**
     * Compile-time dependency graph generated by Metro. Lazily instantiated
     * the first time something asks for a binding (Activity, ViewModel via
     * factory, Worker, etc.). The whole object graph — DataSources, Repos,
     * Managers, UseCases — flows from this single root.
     */
    val appGraph: AppGraph by lazy {
        createGraphFactory<AppGraph.Factory>().create(this)
    }

    override fun onCreate() {
        super.onCreate()
        SingletonImageLoader.setSafe { context ->
            ImageLoader.Builder(context)
                .components { add(SvgDecoder.Factory()) }
                .build()
        }
    }
}
